name: student_art_collection
description: An application that allows student artwork to be sold and bought.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  equatable: ^1.0.1
  firebase_core: ^0.4.3+1
  firebase_auth: ^0.15.3
  dartz: ^0.8.9
  data_connection_checker: ^0.3.4
  moor_flutter: ^2.0.0
  dio: ^3.0.7
  flutter_bloc: ^3.1.0
  get_it: ^3.0.3
  extended_image: ^0.6.8
  flutter_screenutil: ^0.7.0
  flutter_staggered_grid_view: ^0.3.0
  flutter_swiper: ^1.1.6
  carousel_slider: ^1.4.0
  graphql: ^3.0.0
  cached_network_image: ^2.0.0
  flutter_picker: ^1.1.0
  cloudinary_client: ^0.0.9
  image_picker: ^0.6.3
  titled_navigation_bar: ^3.6.0
  device_preview: ^0.2.6
  flutter_image_compress: ^0.6.5
  shared_preferences: ^0.5.6
  email_validator: ^1.0.4
  awesome_dialog: ^0.1.0
  flutter_svg: ^0.15.0
  flutter_inner_drawer: ^0.5.4
  grouped_buttons: ^1.0.4
  geolocator: ^5.2.0
  geocoder: ^0.2.1
  flutter_launcher_icons: ^0.7.4

dev_dependencies:
  intl_translation: ^0.17.9
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/artco_icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - lang/
    - secrets.json
