name: student_art_collection
description: An application that allows student artwork to be sold and bought.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  equatable: ^1.0.1
  firebase_core: ^0.4.3+1
  firebase_auth: ^0.15.3
  dartz: ^0.8.9
  data_connection_checker: ^0.3.4
  moor_flutter: ^2.0.0
  dio: ^3.0.7
  flutter_bloc: ^2.1.1
  get_it: ^3.0.3
  extended_image: ^0.6.8
  flutter_screenutil: ^0.7.0
  flutter_staggered_grid_view: ^0.3.0
  flutter_swiper: ^1.1.6
  graphql_flutter: ^2.1.1-beta.5
  graphql: ^2.1.1-beta.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

flutter:

  uses-material-design: true

  assets:
    - images/
